import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

const NAVY  = [27, 42, 74]
const GOLD  = [212, 160, 23]
const WHITE = [255, 255, 255]
const GRAY  = [248, 249, 250]

function addHeader(doc, title, subtitle) {
  doc.setFillColor(...NAVY)
  doc.rect(0, 0, 210, 30, 'F')
  doc.setTextColor(...WHITE)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('MineManager XPL', 14, 12)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Celestium Corporate Ltd · 140 TPH Alluvial Scrubber Plant · Dande, Zimbabwe', 14, 19)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, 26)
  if (subtitle) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, 140, 26)
  }
  return 38
}

function addSection(doc, y, title) {
  doc.setFillColor(...GOLD)
  doc.rect(14, y, 182, 7, 'F')
  doc.setTextColor(...NAVY)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(title.toUpperCase(), 16, y + 5)
  return y + 10
}

export function generateHandoverPDF(handover) {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Shift Handover Report', format(new Date(), 'dd/MM/yyyy HH:mm'))
  y = addSection(doc, y, 'Shift Information')
  const info = [
    ['Date', handover.date || '—', 'Shift', handover.shift || '—'],
    ['Outgoing Supervisor', handover.outgoing_supervisor_id || '—', 'Incoming Supervisor', handover.incoming_supervisor_id || '—'],
    ['Overall Status', handover.overall_status || '—', 'Workers On Site', handover.workers_on_site || '—']
  ]
  autoTable(doc, { startY: y, body: info, theme: 'plain', styles: { fontSize: 9 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 }, 2: { fontStyle: 'bold', cellWidth: 45 } } })
  y = doc.lastAutoTable.finalY + 5

  y = addSection(doc, y, 'Production')
  autoTable(doc, {
    startY: y,
    head: [['Ore Processed (t)', 'Gold Recovered (g)', 'Workers On Site']],
    body: [[handover.ore_processed || '0', handover.gold_recovered_g || '0', handover.workers_on_site || '0']],
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 9 },
    styles: { fontSize: 10, halign: 'center' }
  })
  y = doc.lastAutoTable.finalY + 5

  const sections = [
    ['Incidents Summary', handover.incidents_summary],
    ['Equipment Status', handover.equipment_status],
    ['Outstanding Tasks', handover.outstanding_tasks],
    ['Safety Notes', handover.safety_notes]
  ]
  sections.forEach(([title, text]) => {
    if (y > 260) { doc.addPage(); y = 15 }
    y = addSection(doc, y, title)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)
    const lines = doc.splitTextToSize(text || 'None recorded.', 182)
    doc.text(lines, 14, y)
    y += lines.length * 5 + 6
  })

  y += 10
  doc.setDrawColor(...NAVY)
  doc.line(14, y, 100, y); doc.line(110, y, 196, y)
  doc.setFontSize(8); doc.setTextColor(150, 150, 150)
  doc.text('Outgoing Supervisor Signature', 14, y + 6)
  doc.text('Incoming Supervisor Signature', 110, y + 6)

  doc.save(`handover-${handover.date}-${handover.shift}.pdf`)
}

export function generateDailyReport({ date, handovers, production, incidents, si91, generatedBy }) {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Daily Shift Report', `${date} · Generated by ${generatedBy}`)

  // SI 91
  y = addSection(doc, y, 'SI 91 Daily Confirmation')
  const si91Row = si91?.[0]
  autoTable(doc, {
    startY: y,
    body: [[si91Row ? `✓ Confirmed by ${si91Row.confirmed_by} at ${format(new Date(si91Row.timestamp), 'HH:mm')}` : '✗ NOT CONFIRMED']],
    theme: 'plain',
    styles: { fontSize: 10, textColor: si91Row ? [46, 125, 50] : [220, 38, 38], fontStyle: 'bold' }
  })
  y = doc.lastAutoTable.finalY + 5

  // Production
  y = addSection(doc, y, 'Production Summary')
  const prod = production || []
  const totTonnes = prod.reduce((s, r) => s + (parseFloat(r.ore_processed) || 0), 0)
  const totGold = prod.reduce((s, r) => s + (parseFloat(r.total_gold_g) || 0), 0)
  const totRuntime = prod.reduce((s, r) => s + (parseFloat(r.plant_runtime_hrs) || 0), 0)
  autoTable(doc, {
    startY: y,
    head: [['Ore Processed (t)', 'Gold Recovered (g)', 'Plant Run-Time (hrs)']],
    body: [[totTonnes.toFixed(1), totGold.toFixed(2), totRuntime.toFixed(1)]],
    headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 9 },
    styles: { fontSize: 11, halign: 'center', fontStyle: 'bold' }
  })
  y = doc.lastAutoTable.finalY + 5

  // Handovers
  if (handovers?.length > 0) {
    y = addSection(doc, y, 'Shift Handovers')
    autoTable(doc, {
      startY: y,
      head: [['Shift', 'Outgoing', 'Incoming', 'Ore (t)', 'Gold (g)', 'Status']],
      body: handovers.map(h => [h.shift, h.outgoing_supervisor_id, h.incoming_supervisor_id, h.ore_processed || 0, h.gold_recovered_g || 0, h.overall_status]),
      headStyles: { fillColor: NAVY, textColor: WHITE, fontSize: 8 },
      styles: { fontSize: 8 }
    })
    y = doc.lastAutoTable.finalY + 5
  }

  // Incidents
  const todayIncidents = (incidents || []).filter(i => i.date === date)
  if (todayIncidents.length > 0) {
    if (y > 220) { doc.addPage(); y = 15 }
    y = addSection(doc, y, `Incidents (${todayIncidents.length})`)
    autoTable(doc, {
      startY: y,
      head: [['Time', 'Type', 'Severity', 'Description', 'Status']],
      body: todayIncidents.map(i => [i.time, i.type, i.severity, i.description?.substring(0, 60), i.status]),
      headStyles: { fillColor: [220, 38, 38], textColor: WHITE, fontSize: 8 },
      styles: { fontSize: 8 }
    })
    y = doc.lastAutoTable.finalY + 5
  }

  doc.save(`daily-report-${date}.pdf`)
}

export function generateWeeklyReport({ handovers, production, incidents, generatedBy }) {
  const doc = new jsPDF()
  const weekEnd = format(new Date(), 'yyyy-MM-dd')
  let y = addHeader(doc, 'Weekly Summary Report', `Week ending ${weekEnd} · ${generatedBy}`)

  // Last 7 days production
  y = addSection(doc, y, '7-Day Production Summary')
  const last7 = (production || []).slice(-14)
  const totTonnes = last7.reduce((s, r) => s + (parseFloat(r.ore_processed) || 0), 0)
  const totGold = last7.reduce((s, r) => s + (parseFloat(r.total_gold_g) || 0), 0)
  autoTable(doc, {
    startY: y,
    head: [['Total Ore (t)', 'Total Gold (g)', 'Shifts Logged']],
    body: [[totTonnes.toFixed(1), totGold.toFixed(2), last7.length]],
    headStyles: { fillColor: NAVY, textColor: WHITE },
    styles: { fontSize: 11, halign: 'center', fontStyle: 'bold' }
  })
  y = doc.lastAutoTable.finalY + 5

  if (last7.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Shift', 'Run-Time (hrs)', 'Ore (t)', 'Gold (g)']],
      body: last7.map(r => [r.date, r.shift, r.plant_runtime_hrs || '—', r.ore_processed || 0, r.total_gold_g || 0]),
      headStyles: { fillColor: GRAY, textColor: NAVY, fontSize: 8 },
      styles: { fontSize: 8 }
    })
    y = doc.lastAutoTable.finalY + 5
  }

  // Open incidents
  const openInc = (incidents || []).filter(i => i.status === 'Open')
  if (openInc.length > 0) {
    if (y > 200) { doc.addPage(); y = 15 }
    y = addSection(doc, y, `Open Incidents (${openInc.length})`)
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Type', 'Severity', 'Description']],
      body: openInc.map(i => [i.date, i.type, i.severity, i.description?.substring(0, 70)]),
      headStyles: { fillColor: [220, 38, 38], textColor: WHITE, fontSize: 8 },
      styles: { fontSize: 8 }
    })
  }

  doc.save(`weekly-report-${weekEnd}.pdf`)
}
